uploads = []
generated = []

[[outputs]]
id = "7tHWAGpB4OHjW685uoMuG"
uri = "file://RecebMed_Technical_Audit.md"
type = "text"
title = "RecebMed - Auditoria Técnica v2.0 (Baseada na Produção)"

[[outputs]]
id = "jXdG3gqF_gEQeH3Qo5Wao"
uri = "file://RecebMed_Technical_Audit_Report.md"
type = "text"
title = "RecebMed — Relatório Técnico de Auditoria"

[[outputs]]
id = "xgVYZ9WJGhs9jSFwECb16"
uri = "file://RecebMed_Final_Engineering_Audit_Report.md"
type = "text"
title = "RecebMed — Final Engineering Audit Report"

[[outputs]]
id = "mUNkU2-ZoWYJWDePDTAZP"
uri = "file://RecebMed_UX_UI_Audit_Report.md"
type = "text"
title = "RecebMed — Auditoria Completa de UX/UI"
